name: Snapshot
'on':
  pull_request:
    branches:
    - main
    - next-minor
    - next-major
  workflow_dispatch: null
permissions: {}
jobs:
  snapshot:
    name: Snapshot
    if: github.repository_owner == 'playground-nils'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      uses: ./.github/actions/setup
    - name: Run codemods
      run: bun codemod
    - name: Build package
      run: bun run build
    - name: Create snapshot
      id: snapshot
      run: bunx pkg-pr-new@0.0.28 publish --bun --comment=off ./packages/*
